Do not make sbt versions equal. Still fails:
[info] loading project definition from /home/vexriscv/project/try/VexRiscv/project
/home/vexriscv/project/try/VexRiscv/build.sbt:7: error: type mismatch;
 found   : sbt.SettingKey[String]
 required: String
      scalaVersion := "2.11.12",
      ^
sbt.compiler.EvalException: Type error in expression